# -*- coding: utf-8 -*-
"""01_exploratory_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bJiPu4D11Xti7HDwWHMkH63Cm9EZItz
"""

import pandas as pd

df = pd.read_csv('/content/creditcard.csv')

"""### Display the first few rows of the DataFrame to get an initial look at the data."""

display(df.head())

"""### Get a concise summary of the DataFrame, including data types and non-null values."""

display(df.info())

"""### Generate descriptive statistics to summarize the central tendency, dispersion, and shape of the dataset's distribution."""

display(df.describe())

"""### Check for any missing values in the DataFrame."""

display(df.isnull().sum())

"""### Handling Missing Values: Dropping rows with any null values."""

df_cleaned = df.dropna()
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

df = df_cleaned.copy()

"""### Verify that all missing values have been removed."""

display(df.isnull().sum())

"""### Display the class distribution to check for imbalance."""

display(df['Class'].value_counts())
display(df['Class'].value_counts(normalize=True) * 100)

"""### Feature Scaling: Standardizing 'Time' and 'Amount' columns."""

from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale 'Time' and 'Amount' columns
df['Time'] = scaler.fit_transform(df[['Time']])
df['Amount'] = scaler.fit_transform(df[['Amount']])

# Display descriptive statistics for the scaled columns to verify
print("Descriptive statistics after scaling 'Time' and 'Amount':")
display(df[['Time', 'Amount']].describe())

"""With feature scaling applied, the data is now more prepared for modeling. The next critical step, especially given the noted class imbalance in the 'Class' column, is to address this imbalance. This is important to ensure that any predictive model doesn't simply ignore the minority (fraudulent) class. Would you like to proceed with handling the class imbalance next?

### Handling Class Imbalance with SMOTE
"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data (optional, but good for continued EDA if needed)
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

"""Now that the class imbalance has been addressed, the dataset is more balanced and ready for model training. What would you like to do next? We could:

1.  Split the data into training and testing sets.
2.  Visualize some features to understand their distributions better.
3.  Move directly to model selection and training.

### Displaying the total number of rows and columns in the DataFrame.
"""

num_rows, num_cols = df.shape
print(f"The DataFrame has {num_rows} rows (data entries) and {num_cols} columns.")