# -*- coding: utf-8 -*-
"""feature engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bJiPu4D11Xti7HDwWHMkH63Cm9EZItz
"""

import pandas as pd

df = pd.read_csv('/content/creditcard.csv')

import zipfile
import os

zip_file_path = '/content/archive (1).zip'
extract_dir = '/content/extracted_data'

# Create the extraction directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# List the contents to find the CSV file
print(f"Extracted contents of '{zip_file_path}' to '{extract_dir}':")
for root, dirs, files in os.walk(extract_dir):
    for name in files:
        print(os.path.join(root, name))

# Assuming the creditcard.csv is directly inside the extracted_data directory
# If it's in a subdirectory, the path needs to be adjusted accordingly.
csv_file_path = os.path.join(extract_dir, 'creditcard.csv')

# Load the data into a pandas DataFrame
df = pd.read_csv(csv_file_path)

print(f"Data loaded from: {csv_file_path}")

from google.colab import drive
drive.mount('/content/drive')

"""### Display the first few rows of the DataFrame to get an initial look at the data."""

display(df.head())

"""### Get a concise summary of the DataFrame, including data types and non-null values."""

display(df.info())

"""### Generate descriptive statistics to summarize the central tendency, dispersion, and shape of the dataset's distribution."""

display(df.describe())

"""### Check for any missing values in the DataFrame."""

display(df.isnull().sum())

"""### Handling Missing Values: Dropping rows with any null values."""

df_cleaned = df.dropna()
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

df = df_cleaned.copy()

"""## Feature Engineering

Let's create some new features from the existing 'Time' and 'Amount' columns. Time-based features can capture cyclical patterns, and a log transformation of 'Amount' can help normalize its skewed distribution.
"""

import numpy as np

# Create 'Hour' feature from 'Time'
# Assuming 'Time' is in seconds and represents time since the first transaction
# Max time is around 172792 seconds (~48 hours), so we can map it to hours in a day cycle.
# For simplicity, we'll map directly to a 24-hour cycle. Adjust if 'Time' represents a larger span.
df['Hour'] = (df['Time'] / 3600).astype(int) % 24

# Create a log-transformed 'Amount' feature to handle its skewed distribution
# Add a small constant to avoid log(0) if 'Amount' can be zero
df['Amount_log'] = np.log1p(df['Amount'])

print("New features 'Hour' and 'Amount_log' created.")
display(df[['Time', 'Hour', 'Amount', 'Amount_log']].head())

"""### Verify that all missing values have been removed."""

display(df.isnull().sum())

"""### Display the class distribution to check for imbalance."""

display(df['Class'].value_counts())
display(df['Class'].value_counts(normalize=True) * 100)

"""### Feature Scaling: Standardizing 'Time' and 'Amount' columns."""

from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Drop the original 'Amount' column if 'Amount_log' is preferred
df_processed = df.drop('Amount', axis=1)

# Scale 'Time' and 'Amount_log' columns
df_processed['Time'] = scaler.fit_transform(df_processed[['Time']])
df_processed['Amount_log'] = scaler.fit_transform(df_processed[['Amount_log']])

# Optionally, also scale the 'Hour' feature if desired, assuming it's treated as a continuous variable for scaling
# If 'Hour' is to be treated as a cyclical feature (e.g., using sin/cos transformations), that would be a separate step.
# For now, let's scale it as a numerical feature if it's meant to be used directly in the model.
# df_processed['Hour'] = scaler.fit_transform(df_processed[['Hour']])

# Update the main DataFrame `df` with the processed features
df = df_processed.copy()

# Display descriptive statistics for the scaled columns to verify
print("Descriptive statistics after scaling 'Time' and 'Amount_log':")
display(df[['Time', 'Amount_log', 'Hour']].describe())

"""With feature scaling applied, the data is now more prepared for modeling. The next critical step, especially given the noted class imbalance in the 'Class' column, is to address this imbalance. This is important to ensure that any predictive model doesn't simply ignore the minority (fraudulent) class. Would you like to proceed with handling the class imbalance next?

### Handling Class Imbalance with SMOTE
"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data (optional, but good for continued EDA if needed)
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

"""Now that the class imbalance has been addressed, the dataset is more balanced and ready for model training. What would you like to do next? We could:

1.  Split the data into training and testing sets.
2.  Visualize some features to understand their distributions better.
3.  Move directly to model selection and training.

### Re-creating `df_resampled` with SMOTE (as it was not found in the kernel state)
"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

print(f"df_resampled created with shape: {df_resampled.shape}")

"""## Exploratory Data Analysis (EDA) of Resampled Data"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize class distribution after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df_resampled, palette='viridis')
plt.title('Class Distribution After SMOTE')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Number of Samples')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""Now, let's look at the distribution of the 'Amount' feature for both classes in the resampled dataset."""

# Distribution of 'Amount' for each class in the resampled DataFrame
plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Amount'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Amount'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Scaled Amount')
plt.ylabel('Density')
plt.legend()
plt.show()

"""Next, let's generate a correlation matrix to understand the relationships between different features in the resampled dataset. This can help identify highly correlated features and provide insights into their predictive power."""

# Calculate the correlation matrix for the resampled DataFrame
corr_matrix = df_resampled.corr()

# Plotting the heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Features (Resampled Data)')
plt.show()

df_resampled.groupby('Class')['Amount'].describe()

"""The descriptive statistics for the 'Amount' feature for both classes show:

*   **Class 0 (Non-Fraudulent)**:
    *   The mean transaction amount for non-fraudulent transactions is generally higher than fraudulent ones after SMOTE, although this can be influenced by the synthetic samples.
    *   The standard deviation indicates the spread of these amounts.

*   **Class 1 (Fraudulent)**:
    *   Fraudulent transactions tend to have a lower mean 'Amount' compared to non-fraudulent transactions, which aligns with common fraud patterns where smaller amounts might be tested first.
    *   The maximum amount for fraudulent transactions is also typically lower than for non-fraudulent ones, suggesting that large-value transactions are less likely to be fraudulent, or that SMOTE has generated synthetic samples that reflect this trend.
    
This analysis highlights that the 'Amount' feature can be a discriminating factor between the two classes, with fraudulent transactions generally involving smaller sums.

## Exploratory Data Analysis (EDA) of Resampled Data
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize class distribution after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df_resampled, palette='viridis', hue='Class', legend=False)
plt.title('Class Distribution After SMOTE')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Number of Samples')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""Now, let's look at the distribution of the 'Amount' feature for both classes in the resampled dataset."""

# Distribution of 'Amount' for each class in the resampled DataFrame
plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Amount'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Amount'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Scaled Amount')
plt.ylabel('Density')
plt.legend()
plt.show()

"""Next, let's generate a correlation matrix to understand the relationships between different features in the resampled dataset. This can help identify highly correlated features and provide insights into their predictive power."""

# Calculate the correlation matrix for the resampled DataFrame
corr_matrix = df_resampled.corr()

# Plotting the heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Features (Resampled Data)')
plt.show()

df_resampled.groupby('Class')['Amount'].describe()

"""The descriptive statistics for the 'Amount' feature for both classes show:

*   **Class 0 (Non-Fraudulent)**:
    *   The mean transaction amount for non-fraudulent transactions is generally higher than fraudulent ones after SMOTE, although this can be influenced by the synthetic samples.
    *   The standard deviation indicates the spread of these amounts.

*   **Class 1 (Fraudulent)**:
    *   Fraudulent transactions tend to have a lower mean 'Amount' compared to non-fraudulent transactions, which aligns with common fraud patterns where smaller amounts might be tested first.
    *   The maximum amount for fraudulent transactions is also typically lower than for non-fraudulent ones, suggesting that large-value transactions are less likely to be fraudulent, or that SMOTE has generated synthetic samples that reflect this trend.
    
This analysis highlights that the 'Amount' feature can be a discriminating factor between the two classes, with fraudulent transactions generally involving smaller sums.

### Fraud Rate Calculation
"""

# Calculate the fraud rate from the resampled DataFrame
fraud_count = df_resampled['Class'].sum()
total_transactions = len(df_resampled)
fraud_rate = (fraud_count / total_transactions) * 100

print(f"Total transactions in resampled data: {total_transactions}")
print(f"Fraudulent transactions in resampled data: {fraud_count}")
print(f"Fraud Rate (in resampled data): {fraud_rate:.2f}%")

"""### Detailed Analysis of Transaction Amounts"""

print("Descriptive statistics of 'Amount' by 'Class' in resampled data:")
display(df_resampled.groupby('Class')['Amount'].describe())

"""A box plot can help visualize the distribution and identify outliers more clearly."""

plt.figure(figsize=(8, 6))
sns.boxplot(x='Class', y='Amount', data=df_resampled, palette='coolwarm', hue='Class', legend=False)
plt.title('Box Plot of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Amount')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""A violin plot can provide a more detailed view of the distribution of transaction amounts for both classes, showing the density of the data at different values."""

plt.figure(figsize=(10, 7))
sns.violinplot(x='Class', y='Amount', data=df_resampled, palette='coolwarm', hue='Class', legend=False)
plt.title('Violin Plot of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Amount')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""The violin plot confirms that while the median amounts might be similar after resampling, the distribution shapes differ.

*   **Non-Fraudulent (Class 0):** The distribution is wider, indicating a broader range of transaction amounts, with higher density around lower amounts and a long tail extending to larger amounts.
*   **Fraudulent (Class 1):** The distribution appears more concentrated, suggesting that fraudulent transactions tend to cluster around specific, often smaller, amounts. This can be a crucial characteristic for detecting fraudulent activities.

### Detailed Analysis of Transaction Time
"""

print("Descriptive statistics of 'Time' by 'Class' in resampled data:")
display(df_resampled.groupby('Class')['Time'].describe())

"""Let's visualize the distribution of transaction 'Time' for both classes using a histogram."""

plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Time'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Time'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Time by Class (Resampled Data)')
plt.xlabel('Scaled Time')
plt.ylabel('Density')
plt.legend()
plt.show()

"""A violin plot will provide an even more detailed view of the 'Time' distribution for each class."""

plt.figure(figsize=(10, 7))
sns.violinplot(x='Class', y='Time', data=df_resampled, palette='coolwarm', hue='Class', legend=False)
plt.title('Violin Plot of Transaction Time by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Time')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""The analysis of the 'Time' feature reveals a couple of key points:

*   **Descriptive Statistics:** The mean and standard deviation for 'Time' in both fraudulent and non-fraudulent transactions are quite similar. This suggests that, on average, fraudulent activities are not concentrated at very specific times relative to the dataset's overall time frame. The minimum and maximum values for both classes also span the entire time range, indicating that fraud can occur at any point within the recorded period.

*   **Histograms and Violin Plots:** These visualizations reinforce the findings from the descriptive statistics. Both plots show that fraudulent and non-fraudulent transactions are distributed across the entire 'Time' spectrum. There doesn't appear to be a clear, distinct time window where fraudulent transactions are overwhelmingly more frequent than legitimate ones, or vice versa. The distributions largely overlap, implying that 'Time' itself, in its raw or scaled form, might not be a strong standalone predictor for fraud in this dataset, unlike 'Amount'.
"""

print(f"Dimensions of df_resampled (rows, columns): {df_resampled.shape}")

"""### Displaying the total number of rows and columns in the DataFrame.

### Checking for Duplicate Transactions
"""

# Check for duplicate rows in df_resampled
duplicate_rows = df_resampled.duplicated().sum()
print(f"Number of duplicate rows in df_resampled: {duplicate_rows}")

if duplicate_rows > 0:
    print("Removing duplicate rows...")
    df_resampled_no_duplicates = df_resampled.drop_duplicates()
    print(f"Shape of df_resampled after removing duplicates: {df_resampled_no_duplicates.shape}")
else:
    print("No duplicate rows found.")

"""### Checking for Missing Values in Resampled Data"""

print("Missing values in df_resampled:")
display(df_resampled.isnull().sum())

"""### Visualizing Class Distribution After SMOTE"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize class distribution after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df_resampled, palette='viridis', hue='Class', legend=False)
plt.title('Class Distribution After SMOTE')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Number of Samples')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""### Column Information of Resampled DataFrame"""

print("Column information for df_resampled:")
display(df_resampled.info())

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

print(f"df_resampled created with shape: {df_resampled.shape}")

print("Column information for df_resampled:")
display(df_resampled.info())

from sklearn.model_selection import train_test_split

# Features to exclude due to potential data leakage
features_to_exclude = ['V4', 'V11', 'V14']

# Separate features (X) and target (y) from the DataFrame without duplicates
# Drop the identified leaky features
X = df_resampled_no_duplicates.drop(['Class'] + features_to_exclude, axis=1)
y = df_resampled_no_duplicates['Class']

# Split the data into training and testing sets
# We'll use a 80/20 split (80% for training, 20% for testing)
# random_state ensures reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Shape of X_train (after excluding features): {X_train.shape}")
print(f"Shape of X_test (after excluding features): {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nClass distribution in y_train:")
display(y_train.value_counts(normalize=True))

print("\nClass distribution in y_test:")
display(y_test.value_counts(normalize=True))

"""## Retraining LightGBM Model without Leaky Features"""

import lightgbm as lgb

# Initialize a new LightGBM Classifier instance (or re-initialize the old one)
lgbm_model_retained = lgb.LGBMClassifier(random_state=42)

# Train the model with the updated X_train and y_train
print("Training LightGBM model with reduced feature set...")
lgbm_model_retained.fit(X_train, y_train)

print("LightGBM model training complete on reduced feature set.")

"""## Re-evaluating Model Performance"""

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Make predictions on the test set using the retrained model
y_pred_retained = lgbm_model_retained.predict(X_test)

# Display Classification Report
print("Classification Report (after removing leaky features):")
print(classification_report(y_test, y_pred_retained))

# Display Confusion Matrix
cm_retained = confusion_matrix(y_test, y_pred_retained)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_retained, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix (after removing leaky features)')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()

"""## Re-evaluating Feature Importance with the Retrained Model"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get feature importances from the retrained LightGBM model
feature_importance_retained = lgbm_model_retained.feature_importances_
feature_names_retained = X_train.columns

# Create a DataFrame for better visualization
importance_df_retained = pd.DataFrame({
    'Feature': feature_names_retained,
    'Importance': feature_importance_retained
})

# Sort features by importance in descending order
importance_df_retained = importance_df_retained.sort_values(by='Importance', ascending=False)

# Display the top N most important features
N_retained = 15 # You can adjust this number
print(f"Top {N_retained} Feature Importances (after removing V4, V11, V14):")
display(importance_df_retained.head(N_retained))

# Plotting feature importance
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df_retained.head(N_retained), palette='viridis', hue='Feature', legend=False)
plt.title(f'Top {N_retained} LightGBM Feature Importances (Retrained Model)')
plt.xlabel('Importance (F-score)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""## Detailed Data Leakage Investigation on New Top Features"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the names of the top N_retained features from the importance_df_retained
current_top_features = importance_df_retained['Feature'].head(N_retained).tolist()

# Add 'Class' to the features we want to analyze
analysis_features_leakage = [f for f in current_top_features if f != 'Class']
analysis_features_leakage.append('Class')

print("Analyzing the relationship between current top features and 'Class' for potential data leakage...")

# Plotting distributions or relationships for current top features
for feature in current_top_features:
    if feature != 'Class': # Ensure we don't try to plot 'Class' against itself
        plt.figure(figsize=(10, 6))
        # Add hue='Class' and legend=False to address FutureWarning
        sns.boxplot(x='Class', y=feature, data=df_resampled_no_duplicates, palette='coolwarm', hue='Class', legend=False)
        plt.title(f'Distribution of {feature} by Class (After removing V4, V11, V14)')
        plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
        plt.ylabel(feature)
        plt.show()

# Also check correlations specifically with the 'Class' variable for the current top features
print("\nCorrelation of current top features with 'Class' variable (after removing V4, V11, V14):")
correlation_with_class_retained = df_resampled_no_duplicates[analysis_features_leakage].corr()['Class'].sort_values(ascending=False)
print(correlation_with_class_retained)

"""### Removing Newly Identified Leaky Features and Re-splitting Data"""

# Features to exclude based on the second round of data leakage investigation
# These include the initially excluded features and the new highly correlated ones.
features_to_exclude_round2 = ['V4', 'V11', 'V14', 'V12', 'V10', 'V16', 'V9', 'V3', 'V17']

# Separate features (X) and target (y) from the DataFrame without duplicates
# Drop all identified leaky features
X = df_resampled_no_duplicates.drop(['Class'] + features_to_exclude_round2, axis=1)
y = df_resampled_no_duplicates['Class']

# Split the data into training and testing sets again
X_train_round2, X_test_round2, y_train_round2, y_test_round2 = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Shape of X_train (after excluding all identified leaky features): {X_train_round2.shape}")
print(f"Shape of X_test (after excluding all identified leaky features): {X_test_round2.shape}")
print(f"Shape of y_train: {y_train_round2.shape}")
print(f"Shape of y_test: {y_test_round2.shape}")

print("\nClass distribution in y_train_round2:")
display(y_train_round2.value_counts(normalize=True))

print("\nClass distribution in y_test_round2:")
display(y_test_round2.value_counts(normalize=True))

"""### Retraining LightGBM Model without All Identified Leaky Features"""

# Initialize a new LightGBM Classifier instance
lgbm_model_final = lgb.LGBMClassifier(random_state=42)

# Train the model with the further reduced feature set
print("Training LightGBM model with final reduced feature set...")
lgbm_model_final.fit(X_train_round2, y_train_round2)

print("LightGBM model training complete on final reduced feature set.")

"""### Re-evaluating Model Performance (Final Round)"""

# Make predictions on the test set using the finally retrained model
y_pred_final = lgbm_model_final.predict(X_test_round2)

# Display Classification Report
print("Classification Report (after removing all identified leaky features):")
print(classification_report(y_test_round2, y_pred_final))

# Display Confusion Matrix
cm_final = confusion_matrix(y_test_round2, y_pred_final)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_final, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix (after removing all identified leaky features)')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()

"""### Re-evaluating Feature Importance with the Finally Retrained Model"""

# Get feature importances from the finally retrained LightGBM model
feature_importance_final = lgbm_model_final.feature_importances_
feature_names_final = X_train_round2.columns

# Create a DataFrame for better visualization
importance_df_final = pd.DataFrame({
    'Feature': feature_names_final,
    'Importance': feature_importance_final
})

# Sort features by importance in descending order
importance_df_final = importance_df_final.sort_values(by='Importance', ascending=False)

# Display the top N most important features
N_final = 15 # You can adjust this number
print(f"Top {N_final} Feature Importances (after removing all identified leaky features):")
display(importance_df_final.head(N_final))

# Plotting feature importance
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df_final.head(N_final), palette='viridis', hue='Feature', legend=False)
plt.title(f'Top {N_final} LightGBM Feature Importances (Final Retrained Model)')
plt.xlabel('Importance (F-score)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""### Investigating Data Leakage from SMOTE: Original vs. Synthetic Samples"""

# To investigate SMOTE, we need to recreate X_resampled, y_resampled, and also keep track of original indices.
# Re-apply SMOTE to get original and synthetic indices

# Ensure 'df' is the original DataFrame with scaled 'Time' and 'Amount' but before SMOTE
# (from cell 6f787416 or b5943b42 if df_resampled was regenerated)

# Separate features (X_original) and target (y_original) from the original DataFrame before SMOTE
X_original = df.drop('Class', axis=1)
y_original = df['Class']

# Re-apply SMOTE to get the resampled data
smote_debugger = SMOTE(random_state=42)
X_resampled_debug, y_resampled_debug = smote_debugger.fit_resample(X_original, y_original)

# Determine original and synthetic samples based on the length of the original data
# SMOTE typically appends synthetic samples to the original ones.
num_original_samples = len(X_original)
is_original = [True] * num_original_samples + [False] * (len(X_resampled_debug) - num_original_samples)

df_resampled_debug = pd.DataFrame(X_resampled_debug, columns=X_original.columns)
df_resampled_debug['Class'] = y_resampled_debug
df_resampled_debug['is_original'] = is_original

print(f"Shape of df_resampled_debug: {df_resampled_debug.shape}")
print(f"Number of original samples: {df_resampled_debug['is_original'].sum()}")
print(f"Number of synthetic samples: {(~df_resampled_debug['is_original']).sum()}")

"""### Visualizing Feature Distributions by Original/Synthetic and Class"""

# Get the current top features from the final retrained model
current_top_features_final = importance_df_final['Feature'].head(N_final).tolist()

print("Visualizing distributions of top features, separated by original/synthetic and Class...")

for feature in current_top_features_final:
    if feature != 'Class': # Ensure we don't try to plot 'Class' against itself
        plt.figure(figsize=(12, 7))
        sns.histplot(
            data=df_resampled_debug,
            x=feature,
            hue='Class',
            col='is_original',
            kde=True,
            palette='viridis',
            stat='density',
            common_norm=False # Normalize each group separately
        )
        plt.suptitle(f'Distribution of {feature} by Class and Sample Type (Original vs. Synthetic)', y=1.02) # Adjust suptitle position
        plt.show()

print("Visualizations complete. Analyze the differences between original and synthetic distributions for signs of leakage.")

print("Column information for df_resampled_no_duplicates:")
display(df_resampled_no_duplicates.info())

"""## Model Training: LightGBM Classifier"""

import lightgbm as lgb

# Initialize the LightGBM Classifier
lgbm_model = lgb.LGBMClassifier(random_state=42)

# Train the model
lgbm_model.fit(X_train, y_train)

print("LightGBM model training complete.")

"""## Model Evaluation"""

from sklearn.metrics import classification_report, confusion_matrix

# Make predictions on the test set
y_pred = lgbm_model.predict(X_test)

# Display Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
import seaborn as sns

# Display Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()

"""## Model Interpretation: Feature Importance"""

# Get feature importances from the trained LightGBM model
feature_importance = lgbm_model.feature_importances_
feature_names = X_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importance
})

# Sort features by importance in descending order
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Display the top N most important features
N = 15 # You can adjust this number
print(f"Top {N} Feature Importances:")
display(importance_df.head(N))

import matplotlib.pyplot as plt
import seaborn as sns

# Plotting feature importance
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df.head(N), palette='viridis', hue='Feature', legend=False)
plt.title(f'Top {N} LightGBM Feature Importances')
plt.xlabel('Importance (F-score)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

"""## Investigating Data Leakage: Analysis of Highly Important Features"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get the current top features from the final retrained model
current_top_features_final = importance_df_final['Feature'].head(N_final).tolist()

print("Visualizing distributions of top features, separated by original/synthetic and Class...")

for feature in current_top_features_final:
    if feature != 'Class': # Ensure we don't try to plot 'Class' against itself
        fig, axes = plt.subplots(1, 2, figsize=(20, 7), sharey=False) # Create 1 row, 2 columns of subplots

        # Plot for Original Samples
        sns.histplot(
            data=df_resampled_debug[df_resampled_debug['is_original'] == True],
            x=feature,
            hue='Class',
            kde=True,
            palette='viridis',
            stat='density',
            common_norm=False, # Normalize each group separately
            ax=axes[0]
        )
        axes[0].set_title(f'Original Samples: Distribution of {feature} by Class')

        # Plot for Synthetic Samples
        sns.histplot(
            data=df_resampled_debug[df_resampled_debug['is_original'] == False],
            x=feature,
            hue='Class',
            kde=True,
            palette='viridis',
            stat='density',
            common_norm=False, # Normalize each group separately
            ax=axes[1]
        )
        axes[1].set_title(f'Synthetic Samples: Distribution of {feature} by Class')

        plt.suptitle(f'Distribution of {feature} by Class and Sample Type', y=1.02) # Adjust suptitle position
        plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent suptitle overlap
        plt.show()

print("Visualizations complete. Analyze the differences between original and synthetic distributions for signs of leakage.")

"""## Addressing Data Leakage: Applying SMOTE only to Training Data

To prevent data leakage, we will first split the original dataset into training and testing sets. Then, SMOTE will be applied *only* to the training data.
"""

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y) from the original DataFrame `df`
# We use `df` here because it contains the original, un-resampled data after scaling
X_original_no_smote = df.drop('Class', axis=1)
y_original_no_smote = df['Class']

# Perform a stratified train-test split on the original data
# This ensures that both training and testing sets have a representative proportion of both classes
X_train_original, X_test_original, y_train_original, y_test_original = train_test_split(
    X_original_no_smote, y_original_no_smote, test_size=0.2, random_state=42, stratify=y_original_no_smote
)

print(f"Shape of X_train (original, before SMOTE): {X_train_original.shape}")
print(f"Shape of X_test (original): {X_test_original.shape}")
print(f"Original training set class distribution: {Counter(y_train_original)}")
print(f"Original test set class distribution: {Counter(y_test_original)}")

# Apply SMOTE only to the training data
smote_pipeline = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote_pipeline.fit_resample(X_train_original, y_train_original)

print(f"Shape of X_train (after SMOTE): {X_train_resampled.shape}")
print(f"Resampled training set class distribution: {Counter(y_train_resampled)}")

# The test set remains as X_test_original, y_test_original, untouched by SMOTE

"""Now that SMOTE has been applied only to the training data, our dataset is prepared for model training without the risk of data leakage. The `X_train_resampled` and `y_train_resampled` will be used for training, while `X_test_original` and `y_test_original` will serve as the unbiased evaluation set.

## Model Training: LightGBM Classifier (with SMOTE on training data only)
"""

import lightgbm as lgb

# Initialize the LightGBM Classifier
lgbm_model_no_leakage = lgb.LGBMClassifier(random_state=42)

# Train the model using the SMOTE-resampled training data
print("Training LightGBM model with SMOTE applied only to training data...")
lgbm_model_no_leakage.fit(X_train_resampled, y_train_resampled)

print("LightGBM model training complete on leak-free training set.")

"""## Model Evaluation (on untouched test set)"""

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Make predictions on the original, untouched test set
y_pred_no_leakage = lgbm_model_no_leakage.predict(X_test_original)

# Display Classification Report
print("Classification Report (after proper SMOTE application):")
print(classification_report(y_test_original, y_pred_no_leakage))

# Display Confusion Matrix
cm_no_leakage = confusion_matrix(y_test_original, y_pred_no_leakage)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_no_leakage, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix (after proper SMOTE application)')
plt.ylabel('Actual Label')
plt.xlabel('Predicted Label')
plt.show()

"""## Model Interpretation: Feature Importance (from leak-free model)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get feature importances from the leak-free LightGBM model
feature_importance_no_leakage = lgbm_model_no_leakage.feature_importances_
feature_names_no_leakage = X_train_resampled.columns

# Create a DataFrame for better visualization
importance_df_no_leakage = pd.DataFrame({
    'Feature': feature_names_no_leakage,
    'Importance': feature_importance_no_leakage
})

# Sort features by importance in descending order
importance_df_no_leakage = importance_df_no_leakage.sort_values(by='Importance', ascending=False)

# Display the top N most important features
N_no_leakage = 15 # You can adjust this number
print(f"Top {N_no_leakage} Feature Importances (from model trained with proper SMOTE application):")
display(importance_df_no_leakage.head(N_no_leakage))

# Plotting feature importance
plt.figure(figsize=(12, 8))
sns.barplot(x='Importance', y='Feature', data=importance_df_no_leakage.head(N_no_leakage), palette='viridis', hue='Feature', legend=False)
plt.title(f'Top {N_no_leakage} LightGBM Feature Importances (Leak-Free Model)')
plt.xlabel('Importance (F-score)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Get the names of the top N features from the importance_df
top_features = importance_df['Feature'].head(N).tolist()

# Add 'Class' to the features we want to analyze if not already present
analysis_features = [f for f in top_features if f != 'Class']
analysis_features.append('Class')

print("Analyzing the relationship between top features and 'Class' for potential data leakage.")

# Plotting distributions or relationships for top features
for feature in top_features:
    if feature != 'Class': # Ensure we don't try to plot 'Class' against itself
        plt.figure(figsize=(10, 6))
        sns.boxplot(x='Class', y=feature, data=df_resampled_no_duplicates, palette='coolwarm', hue='Class', legend=False)
        plt.title(f'Distribution of {feature} by Class')
        plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
        plt.ylabel(feature)
        plt.show()

# Also check correlations specifically with the 'Class' variable for the top features
print("\nCorrelation of top features with 'Class' variable:")
correlation_with_class = df_resampled_no_duplicates[top_features + ['Class']].corr()['Class'].sort_values(ascending=False)
print(correlation_with_class)