# -*- coding: utf-8 -*-
"""Missing-value analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bJiPu4D11Xti7HDwWHMkH63Cm9EZItz
"""

import pandas as pd

df = pd.read_csv('/content/creditcard.csv')

import zipfile
import os

zip_file_path = '/content/archive (1).zip'
extract_dir = '/content/extracted_data'

# Create the extraction directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# List the contents to find the CSV file
print(f"Extracted contents of '{zip_file_path}' to '{extract_dir}':")
for root, dirs, files in os.walk(extract_dir):
    for name in files:
        print(os.path.join(root, name))

# Assuming the creditcard.csv is directly inside the extracted_data directory
# If it's in a subdirectory, the path needs to be adjusted accordingly.
csv_file_path = os.path.join(extract_dir, 'creditcard.csv')

# Load the data into a pandas DataFrame
df = pd.read_csv(csv_file_path)

print(f"Data loaded from: {csv_file_path}")

from google.colab import drive
drive.mount('/content/drive')

"""### Display the first few rows of the DataFrame to get an initial look at the data."""

display(df.head())

"""### Get a concise summary of the DataFrame, including data types and non-null values."""

display(df.info())

"""### Generate descriptive statistics to summarize the central tendency, dispersion, and shape of the dataset's distribution."""

display(df.describe())

"""### Check for any missing values in the DataFrame."""

display(df.isnull().sum())

"""### Handling Missing Values: Dropping rows with any null values."""

df_cleaned = df.dropna()
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

df = df_cleaned.copy()

"""### Verify that all missing values have been removed."""

display(df.isnull().sum())

"""### Display the class distribution to check for imbalance."""

display(df['Class'].value_counts())
display(df['Class'].value_counts(normalize=True) * 100)

"""### Feature Scaling: Standardizing 'Time' and 'Amount' columns."""

from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler
scaler = StandardScaler()

# Scale 'Time' and 'Amount' columns
df['Time'] = scaler.fit_transform(df[['Time']])
df['Amount'] = scaler.fit_transform(df[['Amount']])

# Display descriptive statistics for the scaled columns to verify
print("Descriptive statistics after scaling 'Time' and 'Amount':")
display(df[['Time', 'Amount']].describe())

"""With feature scaling applied, the data is now more prepared for modeling. The next critical step, especially given the noted class imbalance in the 'Class' column, is to address this imbalance. This is important to ensure that any predictive model doesn't simply ignore the minority (fraudulent) class. Would you like to proceed with handling the class imbalance next?

### Handling Class Imbalance with SMOTE
"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data (optional, but good for continued EDA if needed)
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

"""Now that the class imbalance has been addressed, the dataset is more balanced and ready for model training. What would you like to do next? We could:

1.  Split the data into training and testing sets.
2.  Visualize some features to understand their distributions better.
3.  Move directly to model selection and training.

### Re-creating `df_resampled` with SMOTE (as it was not found in the kernel state)
"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Separate features (X) and target (y)
X = df.drop('Class', axis=1)
y = df['Class']

print(f"Original class distribution: {Counter(y)}")

# Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

print(f"Resampled class distribution: {Counter(y_resampled)}")

# Update the DataFrame with the resampled data
df_resampled = pd.DataFrame(X_resampled, columns=X.columns)
df_resampled['Class'] = y_resampled

print(f"df_resampled created with shape: {df_resampled.shape}")

"""## Exploratory Data Analysis (EDA) of Resampled Data"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize class distribution after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df_resampled, palette='viridis')
plt.title('Class Distribution After SMOTE')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Number of Samples')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""Now, let's look at the distribution of the 'Amount' feature for both classes in the resampled dataset."""

# Distribution of 'Amount' for each class in the resampled DataFrame
plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Amount'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Amount'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Scaled Amount')
plt.ylabel('Density')
plt.legend()
plt.show()

"""Next, let's generate a correlation matrix to understand the relationships between different features in the resampled dataset. This can help identify highly correlated features and provide insights into their predictive power."""

# Calculate the correlation matrix for the resampled DataFrame
corr_matrix = df_resampled.corr()

# Plotting the heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Features (Resampled Data)')
plt.show()

df_resampled.groupby('Class')['Amount'].describe()

"""The descriptive statistics for the 'Amount' feature for both classes show:

*   **Class 0 (Non-Fraudulent)**:
    *   The mean transaction amount for non-fraudulent transactions is generally higher than fraudulent ones after SMOTE, although this can be influenced by the synthetic samples.
    *   The standard deviation indicates the spread of these amounts.

*   **Class 1 (Fraudulent)**:
    *   Fraudulent transactions tend to have a lower mean 'Amount' compared to non-fraudulent transactions, which aligns with common fraud patterns where smaller amounts might be tested first.
    *   The maximum amount for fraudulent transactions is also typically lower than for non-fraudulent ones, suggesting that large-value transactions are less likely to be fraudulent, or that SMOTE has generated synthetic samples that reflect this trend.
    
This analysis highlights that the 'Amount' feature can be a discriminating factor between the two classes, with fraudulent transactions generally involving smaller sums.

## Exploratory Data Analysis (EDA) of Resampled Data
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize class distribution after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df_resampled, palette='viridis')
plt.title('Class Distribution After SMOTE')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Number of Samples')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""Now, let's look at the distribution of the 'Amount' feature for both classes in the resampled dataset."""

# Distribution of 'Amount' for each class in the resampled DataFrame
plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Amount'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Amount'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Scaled Amount')
plt.ylabel('Density')
plt.legend()
plt.show()

"""Next, let's generate a correlation matrix to understand the relationships between different features in the resampled dataset. This can help identify highly correlated features and provide insights into their predictive power."""

# Calculate the correlation matrix for the resampled DataFrame
corr_matrix = df_resampled.corr()

# Plotting the heatmap
plt.figure(figsize=(20, 18))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Matrix of Features (Resampled Data)')
plt.show()

df_resampled.groupby('Class')['Amount'].describe()

"""The descriptive statistics for the 'Amount' feature for both classes show:

*   **Class 0 (Non-Fraudulent)**:
    *   The mean transaction amount for non-fraudulent transactions is generally higher than fraudulent ones after SMOTE, although this can be influenced by the synthetic samples.
    *   The standard deviation indicates the spread of these amounts.

*   **Class 1 (Fraudulent)**:
    *   Fraudulent transactions tend to have a lower mean 'Amount' compared to non-fraudulent transactions, which aligns with common fraud patterns where smaller amounts might be tested first.
    *   The maximum amount for fraudulent transactions is also typically lower than for non-fraudulent ones, suggesting that large-value transactions are less likely to be fraudulent, or that SMOTE has generated synthetic samples that reflect this trend.
    
This analysis highlights that the 'Amount' feature can be a discriminating factor between the two classes, with fraudulent transactions generally involving smaller sums.

### Fraud Rate Calculation
"""

# Calculate the fraud rate from the resampled DataFrame
fraud_count = df_resampled['Class'].sum()
total_transactions = len(df_resampled)
fraud_rate = (fraud_count / total_transactions) * 100

print(f"Total transactions in resampled data: {total_transactions}")
print(f"Fraudulent transactions in resampled data: {fraud_count}")
print(f"Fraud Rate (in resampled data): {fraud_rate:.2f}%")

"""### Detailed Analysis of Transaction Amounts"""

print("Descriptive statistics of 'Amount' by 'Class' in resampled data:")
display(df_resampled.groupby('Class')['Amount'].describe())

"""A box plot can help visualize the distribution and identify outliers more clearly."""

plt.figure(figsize=(8, 6))
sns.boxplot(x='Class', y='Amount', data=df_resampled, palette='coolwarm')
plt.title('Box Plot of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Amount')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.show()

"""A violin plot can provide a more detailed view of the distribution of transaction amounts for both classes, showing the density of the data at different values."""

plt.figure(figsize=(10, 7))
sns.violinplot(x='Class', y='Amount', data=df_resampled, palette='coolwarm')
plt.title('Violin Plot of Transaction Amount by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Amount')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""The violin plot confirms that while the median amounts might be similar after resampling, the distribution shapes differ.

*   **Non-Fraudulent (Class 0):** The distribution is wider, indicating a broader range of transaction amounts, with higher density around lower amounts and a long tail extending to larger amounts.
*   **Fraudulent (Class 1):** The distribution appears more concentrated, suggesting that fraudulent transactions tend to cluster around specific, often smaller, amounts. This can be a crucial characteristic for detecting fraudulent activities.

### Detailed Analysis of Transaction Time
"""

print("Descriptive statistics of 'Time' by 'Class' in resampled data:")
display(df_resampled.groupby('Class')['Time'].describe())

"""Let's visualize the distribution of transaction 'Time' for both classes using a histogram."""

plt.figure(figsize=(10, 6))
sns.histplot(df_resampled[df_resampled['Class'] == 0]['Time'], color='blue', kde=True, label='Class 0 (Non-Fraud)', stat='density', alpha=0.5)
sns.histplot(df_resampled[df_resampled['Class'] == 1]['Time'], color='red', kde=True, label='Class 1 (Fraud)', stat='density', alpha=0.5)
plt.title('Distribution of Transaction Time by Class (Resampled Data)')
plt.xlabel('Scaled Time')
plt.ylabel('Density')
plt.legend()
plt.show()

"""A violin plot will provide an even more detailed view of the 'Time' distribution for each class."""

plt.figure(figsize=(10, 7))
sns.violinplot(x='Class', y='Time', data=df_resampled, palette='coolwarm')
plt.title('Violin Plot of Transaction Time by Class (Resampled Data)')
plt.xlabel('Class (0: Non-Fraud, 1: Fraud)')
plt.ylabel('Scaled Time')
plt.xticks(ticks=[0, 1], labels=['Non-Fraud', 'Fraud'])
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""The analysis of the 'Time' feature reveals a couple of key points:

*   **Descriptive Statistics:** The mean and standard deviation for 'Time' in both fraudulent and non-fraudulent transactions are quite similar. This suggests that, on average, fraudulent activities are not concentrated at very specific times relative to the dataset's overall time frame. The minimum and maximum values for both classes also span the entire time range, indicating that fraud can occur at any point within the recorded period.

*   **Histograms and Violin Plots:** These visualizations reinforce the findings from the descriptive statistics. Both plots show that fraudulent and non-fraudulent transactions are distributed across the entire 'Time' spectrum. There doesn't appear to be a clear, distinct time window where fraudulent transactions are overwhelmingly more frequent than legitimate ones, or vice versa. The distributions largely overlap, implying that 'Time' itself, in its raw or scaled form, might not be a strong standalone predictor for fraud in this dataset, unlike 'Amount'.

### Displaying the total number of rows and columns in the DataFrame.

### Checking for Duplicate Transactions
"""

# Check for duplicate rows in df_resampled
duplicate_rows = df_resampled.duplicated().sum()
print(f"Number of duplicate rows in df_resampled: {duplicate_rows}")

if duplicate_rows > 0:
    print("Removing duplicate rows...")
    df_resampled_no_duplicates = df_resampled.drop_duplicates()
    print(f"Shape of df_resampled after removing duplicates: {df_resampled_no_duplicates.shape}")
else:
    print("No duplicate rows found.")

"""### Checking for Missing Values in Resampled Data"""

print("Missing values in df_resampled:")
display(df_resampled.isnull().sum())